branches:
  only:
    - master

language: python
notifications:
  email: false
python:
  - "2.7"
  - "2.6"
before_install :
  - sudo apt-get install -qq 
language: python
notifications:
  email: false
python:
  - "2.7"
  - "2.6"
before_install :
  - sudo apt-get install -qq libboost-dev
install:
  - pip install -r --use-mirrors requirements.txt
  - python setup.py install
script: true
